import type { Appointment } from "../types/calendar";

export const WEEKDAY_LABELS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

export const INITIAL_VISIBLE_MONTH = new Date(2026, 4, 1);
export const INITIAL_SELECTED_DATE_ISO = "2026-05-16";

export const APPOINTMENTS_BY_DATE: Record<string, Appointment[]> = {
  "2026-05-05": [
    {
      id: "a-0501",
      patientName: "Ariana Blake",
      initials: "AB",
      service: "Tooth Cleaning",
      time: "09:00 AM",
      status: "completed",
      age: 31,
      patientId: "A08",
      phone: "+1 (212) 555-0108",
      email: "ariana.blake@email.com",
      visitType: "In-clinic visit",
      notes: "Cleaning completed. No active concerns reported.",
    },
    {
      id: "a-0502",
      patientName: "Noah Patel",
      initials: "NP",
      service: "Orthodontic Follow-up",
      time: "11:30 AM",
      status: "completed",
      age: 25,
      patientId: "A09",
      phone: "+1 (212) 555-0109",
      email: "noah.patel@email.com",
      visitType: "In-clinic visit",
      notes: "Braces progress stable. Continue current aligner plan.",
    },
  ],
  "2026-05-07": [
    {
      id: "a-0701",
      patientName: "Ethan Cole",
      initials: "EC",
      service: "Routine Checkup",
      time: "02:00 PM",
      status: "confirmed",
      age: 43,
      patientId: "A10",
      phone: "+1 (212) 555-0110",
      email: "ethan.cole@email.com",
      visitType: "In-clinic visit",
      notes: "Annual checkup. Evaluate minor gum sensitivity.",
    },
    {
      id: "a-0702",
      patientName: "Maya Lin",
      initials: "ML",
      service: "Scaling",
      time: "03:30 PM",
      status: "completed",
      age: 35,
      patientId: "A14",
      phone: "+1 (212) 555-0114",
      email: "maya.lin@email.com",
      visitType: "In-clinic visit",
      notes: "Scaling completed successfully.",
    },
  ],
  "2026-05-08": [
    {
      id: "a-0801",
      patientName: "Sofia Hall",
      initials: "SH",
      service: "Root Canal Evaluation",
      time: "10:15 AM",
      status: "confirmed",
      age: 39,
      patientId: "A15",
      phone: "+1 (212) 555-0115",
      email: "sofia.hall@email.com",
      visitType: "In-clinic visit",
      notes: "Pain in upper left molar. Requires X-ray review.",
    },
    {
      id: "a-0802",
      patientName: "Ava King",
      initials: "AK",
      service: "Wisdom Tooth Consult",
      time: "12:45 PM",
      status: "pending",
      age: 24,
      patientId: "A16",
      phone: "+1 (212) 555-0116",
      email: "ava.king@email.com",
      visitType: "In-clinic visit",
      notes: "Patient seeking extraction options.",
    },
    {
      id: "a-0803",
      patientName: "Liam White",
      initials: "LW",
      service: "Implant Review",
      time: "04:00 PM",
      status: "confirmed",
      age: 52,
      patientId: "A17",
      phone: "+1 (212) 555-0117",
      email: "liam.white@email.com",
      visitType: "In-clinic visit",
      notes: "Review prior implant healing progression.",
    },
  ],
  "2026-05-12": [
    {
      id: "a-1201",
      patientName: "Harper Ross",
      initials: "HR",
      service: "Veneer Consultation",
      time: "09:45 AM",
      status: "pending",
      age: 29,
      patientId: "A18",
      phone: "+1 (212) 555-0118",
      email: "harper.ross@email.com",
      visitType: "In-clinic visit",
      notes: "Discuss cosmetic veneer plan and timeline.",
    },
    {
      id: "a-1202",
      patientName: "Nina Scott",
      initials: "NS",
      service: "Routine Checkup",
      time: "03:00 PM",
      status: "confirmed",
      age: 34,
      patientId: "A19",
      phone: "+1 (212) 555-0119",
      email: "nina.scott@email.com",
      visitType: "In-clinic visit",
      notes: "Follow-up checkup after cleaning.",
    },
  ],
  "2026-05-13": [
    {
      id: "a-1301",
      patientName: "Luke Morgan",
      initials: "LM",
      service: "Whitening Session",
      time: "01:00 PM",
      status: "pending",
      age: 28,
      patientId: "A20",
      phone: "+1 (212) 555-0120",
      email: "luke.morgan@email.com",
      visitType: "In-clinic visit",
      notes: "First-time whitening consultation.",
    },
  ],
  "2026-05-14": [
    {
      id: "a-1401",
      patientName: "Dylan Hart",
      initials: "DH",
      service: "Cavity Filling",
      time: "10:30 AM",
      status: "confirmed",
      age: 41,
      patientId: "A21",
      phone: "+1 (212) 555-0121",
      email: "dylan.hart@email.com",
      visitType: "In-clinic visit",
      notes: "Small cavity on lower premolar.",
    },
    {
      id: "a-1402",
      patientName: "Emma Fox",
      initials: "EF",
      service: "Dental Crown Prep",
      time: "02:45 PM",
      status: "pending",
      age: 46,
      patientId: "A22",
      phone: "+1 (212) 555-0122",
      email: "emma.fox@email.com",
      visitType: "In-clinic visit",
      notes: "Prepare crown for fractured molar.",
    },
  ],
  "2026-05-16": [
    {
      id: "a-1601",
      patientName: "Zoe Thompson",
      initials: "ZT",
      service: "Routine Checkup",
      time: "01:30 PM",
      status: "confirmed",
      age: 22,
      patientId: "A12",
      phone: "+1 (212) 555-0112",
      email: "zoe.t@email.com",
      visitType: "In-clinic visit",
      notes: "Annual checkup and cleaning.",
    },
    {
      id: "a-1602",
      patientName: "Carlos Rivera",
      initials: "CR",
      service: "Dental Implant Consultation",
      time: "10:00 AM",
      status: "pending",
      age: 58,
      patientId: "A11",
      phone: "+1 (212) 555-0111",
      email: "c.rivera@email.com",
      visitType: "In-clinic visit",
      notes: "Missing lower molar, evaluating implant options.",
    },
  ],
  "2026-05-19": [
    {
      id: "a-1901",
      patientName: "Mia Brooks",
      initials: "MB",
      service: "Oral Exam",
      time: "11:15 AM",
      status: "confirmed",
      age: 37,
      patientId: "A23",
      phone: "+1 (212) 555-0123",
      email: "mia.brooks@email.com",
      visitType: "In-clinic visit",
      notes: "Routine oral exam with gum screening.",
    },
  ],
  "2026-05-20": [
    {
      id: "a-2001",
      patientName: "Oliver Cruz",
      initials: "OC",
      service: "Extraction Follow-up",
      time: "09:30 AM",
      status: "confirmed",
      age: 33,
      patientId: "A24",
      phone: "+1 (212) 555-0124",
      email: "oliver.cruz@email.com",
      visitType: "In-clinic visit",
      notes: "Check healing status post extraction.",
    },
    {
      id: "a-2002",
      patientName: "Grace Kim",
      initials: "GK",
      service: "Retainer Check",
      time: "12:00 PM",
      status: "pending",
      age: 26,
      patientId: "A25",
      phone: "+1 (212) 555-0125",
      email: "grace.kim@email.com",
      visitType: "In-clinic visit",
      notes: "Retainer discomfort and fit adjustment.",
    },
    {
      id: "a-2003",
      patientName: "Leo Nash",
      initials: "LN",
      service: "Deep Cleaning",
      time: "04:15 PM",
      status: "confirmed",
      age: 44,
      patientId: "A26",
      phone: "+1 (212) 555-0126",
      email: "leo.nash@email.com",
      visitType: "In-clinic visit",
      notes: "Deep cleaning with plaque accumulation review.",
    },
  ],
  "2026-05-21": [
    {
      id: "a-2101",
      patientName: "Chloe Diaz",
      initials: "CD",
      service: "Braces Adjustment",
      time: "10:45 AM",
      status: "pending",
      age: 18,
      patientId: "A27",
      phone: "+1 (212) 555-0127",
      email: "chloe.diaz@email.com",
      visitType: "In-clinic visit",
      notes: "Monthly braces tightening appointment.",
    },
    {
      id: "a-2102",
      patientName: "Ryan Bell",
      initials: "RB",
      service: "Checkup",
      time: "03:30 PM",
      status: "confirmed",
      age: 40,
      patientId: "A28",
      phone: "+1 (212) 555-0128",
      email: "ryan.bell@email.com",
      visitType: "In-clinic visit",
      notes: "General checkup and oral hygiene review.",
    },
  ],
  "2026-05-22": [
    {
      id: "a-2201",
      patientName: "Eli Adams",
      initials: "EA",
      service: "Tooth Sensitivity Consult",
      time: "02:15 PM",
      status: "confirmed",
      age: 47,
      patientId: "A29",
      phone: "+1 (212) 555-0129",
      email: "eli.adams@email.com",
      visitType: "In-clinic visit",
      notes: "Sensitivity likely due to enamel wear.",
    },
  ],
  "2026-05-27": [
    {
      id: "a-2701",
      patientName: "Aiden West",
      initials: "AW",
      service: "Mouth Guard Fitting",
      time: "09:00 AM",
      status: "confirmed",
      age: 32,
      patientId: "A30",
      phone: "+1 (212) 555-0130",
      email: "aiden.west@email.com",
      visitType: "In-clinic visit",
      notes: "Custom guard fitting for night grinding.",
    },
    {
      id: "a-2702",
      patientName: "Ivy Young",
      initials: "IY",
      service: "Consultation",
      time: "01:15 PM",
      status: "pending",
      age: 30,
      patientId: "A31",
      phone: "+1 (212) 555-0131",
      email: "ivy.young@email.com",
      visitType: "Teleconsultation",
      notes: "Initial remote consultation request.",
    },
  ],
  "2026-05-28": [
    {
      id: "a-2801",
      patientName: "Nora Quinn",
      initials: "NQ",
      service: "Routine Checkup",
      time: "11:00 AM",
      status: "confirmed",
      age: 36,
      patientId: "A32",
      phone: "+1 (212) 555-0132",
      email: "nora.quinn@email.com",
      visitType: "In-clinic visit",
      notes: "Biannual preventive checkup.",
    },
  ],
};
